### ISSUE TITLE
Add swiping transition between pages

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#114]

**Comment by bastislack** [comment]
Use react-slide-routes and upgrade react-router-dom to v6 (https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6)

**Comment by Felix-Hmpl** [comment]
https://www.reddit.com/r/reactjs/comments/7mfy5i/comment/drtwfc9/?utm_source=share&utm_medium=web2x&context=3
I just found this comment on Reddit and there is some truth to it:
In some browsers, swiping left and right is associated with going back and forth in your browsing history. 
(Swiping to the right to get back to the last site visited...)
If thats so, the swiping feature could get annoying for some users.

**Comment by bastislack** [comment]
True maybe we can try it in the future and see how well it works other wise we can just close it again.

**Comment by bastislack** [comment]
A friend of mine recommended this package: https://swiperjs.com/react
Maybe we can check it out and see if it works smoothly.

**Comment by bastislack** [comment]
I realized this is probably bad practice.
