### ISSUE TITLE
Updated stickFrequency of trick not shown in combo on backbutton

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#115]
If you open a combo and then click on one of the tricks change its frequency and press the backbutton the background color of the trick is not updated in the combo

**Comment by weberax** [comment]
The problem for this is, that once created the tricks in the combo are saved in the combo objects, with their stickfrequency at the time of the combo creation... so changing the stickfrequency later does not affect the tricks in the combo.

To fix this we should save in the combo only the id's of the tricks and then query them later for displaying the combodetails

**Comment by bastislack** [comment]
Are you going to work on this or should I have a look at that?

**Comment by weberax** [comment]
I can do the predefined combos and make a db query for you to query a list of id's.
If you could do the combodetail thing would be great

**Comment by weberax** [comment]
did this in #124 ....

**Comment by weberax** [comment]
@bastislack you opened this issue again?
I thought it should be fixed though #124 

When I try to recreate this everything seems to work

**Comment by bastislack** [comment]
Ah I see. The reason why I opened it is because I tried it in the generator and there the colors are not updated. This is because we save the combo as is in the app state and this does not get updated. Should we try to fix it in the generator as well or would you say we just leave it as it is?
