### ISSUE TITLE
Add recommended prerequisites for tricks

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#116]
Let's add a field of prerequisites so people know which tricks they should work on before trying their dream trick. I guess an array of tricks would make sense e.g. for a 360 Almighty you should have the 360 solid and the Almighty solid.

**Comment by bastislack** [comment]
@weberax If we don't have enough time until the dead line to fully implement this, we should at least have the database ready to support this.

**Comment by weberax** [comment]
we can also easily later implement this into the db without breaking anything.
Should we also really include this in the first beta milestone? I mean we might got some other stuff to focus on first.
I would be nice if we could adjust the milestone to the things we are going to be able to do in time...

**Comment by bastislack** [comment]
I agree with only putting the issues on the milestone that we can complete in time. If adding that feature in later doesn't cause any issues I will remove it from the milestone.

**Comment by bastislack** [comment]
@weberax I just updated the google sheet, now we need to put it in the db.

**Comment by weberax** [comment]
This is done ... now we have to just integrate this into the UI. 
@bastislack is there already an issue? or can you make one
