### ISSUE TITLE
FAB on ios looks weird

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#121]
![FAB_Ios_looks_weird](https://user-images.githubusercontent.com/74077179/145488558-cc2e2550-1da7-44ff-9ac0-3d2f0481ad08.jpeg)

**Comment by Felix-Hmpl** [comment]
The fab is now generated using a library instead of pure css. 
I can't test it on a iOS device right now, but I will do so tomorrow

**Comment by Felix-Hmpl** [comment]
9acda068a4a2167d9f165d7203b31b741765e8b9

**Comment by Felix-Hmpl** [comment]
Seems to be working on iOS
