### ISSUE TITLE
FAB hides trick

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#122]
![FAB_hides_trick](https://user-images.githubusercontent.com/74077179/145488629-9e90dda5-f8ed-4728-a692-7683cdb529cc.jpeg)

**Comment by Felix-Hmpl** [comment]
Made FAB a little transparent in 9acda068a4a2167d9f165d7203b31b741765e8b9
I also used a library to create the FAB instead of pure css. Maybe this fixes it on iOS? Will test it tomorrow
