### ISSUE TITLE
Switching tabs takes some time

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#125]
When going e.g. from Tricks to Combos the UI blocks for a short amount of time which impacts the user experience.

**Comment by bastislack** [comment]
@rorystephenson It seems like everytime a link in the bottom nav is clicked the app gets reloaded. This explains the slow switch between tabs and also the issue in #131. Do you have an idea where it could come from (maybe webpack config stuff?)?

**Comment by rorystephenson** [comment]
> @rorystephenson It seems like everytime a link in the bottom nav is clicked the app gets reloaded. This explains the slow switch between tabs and also the issue in #131. Do you have an idea where it could come from (maybe webpack config stuff?)?

Hmm strange. Do you know if this is new behaviour or if it was happening before my changes?

I'm not immediately sure why my changes would affect this but I changed a fair bit of code so its definitely possible. I'll try to give it a look soon!

**Comment by bastislack** [comment]
I just checked again and it was indeed introduced in your commit. At the first glance the webpack config file is the one that might be the source of the bug, but I also haven't had a detailed look at it.

**Comment by rorystephenson** [comment]
I finally got some time to have a look. It was quite an easy fix, I didn't know that react relies on you using the `Link` component for linking in order for it to avoid refreshing the page and instead just replace the relevant part. Should be fixed on the main branch now.
