### ISSUE TITLE
Bottom Navbar not visible on iPad

### ISSUE THREAD

**Issue by Felix-Hmpl** [bastislack/highline-freestyle#128]
On my iPad the bottom Navbar is not visible.

**Comment by bastislack** [comment]
![IMG-20211213-WA0010](https://user-images.githubusercontent.com/74077179/145988936-add235d0-8a97-4d71-ab09-898355df5fc9.jpg)
On my mum's phone (android) it's also not pinned at the bottom of the screen. It only appears at the very bottom when scrolling down.

**Comment by rorystephenson** [comment]
Hmm sounds like mistakes with my changes. I'll give it a look soon when I get a chance.

**Comment by Felix-Hmpl** [comment]
So when i download it on my ipad it works fine, but in the browser (Safari) there are some issues

**Comment by rorystephenson** [comment]
I think it should be fixed now but I'll wait for you to try on ipad/iPhone to confirm. On android it's working fine.

It turns out that the vh css attribute is handled weirdly on mobile, more info here: https://github.com/bastislack/highline-freestyle/commit/d329db3826d173870408396b6c651bc579b01c9d

**Comment by rorystephenson** [comment]
Closing as I think this is done but feel free to re-open if there's an issue.
