### ISSUE TITLE
Tricks like Backbounce have two bounces.

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#138]
This kind of breaks the logic that a trick only is what happens in between one bounce. Should we just accept that and put e.g. Backbounce from STAND to STAND as a trick? The alternative would be to separate it into two transitions (from STAND to BACK and from BACK to STAND) but displaying it like this in combos would make it confusing for the user.

**Comment by weberax** [comment]
I would say backbounce as a trick is the transition from feet to back...

**Comment by bastislack** [comment]
But e.g. David has the combo Backbounce -> Almighty to other stuff. This would make his combo Feet to Back -> Back to Feet -> Almighty ->..., which drops the combo stats quite a bit. But I think I would also kind of keep the concept of a trick being what happens in one bounce. Just wanted to have your opinions on it.
