### ISSUE TITLE
changing default branch of repository

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#158]
I think we should change the `develop` branch to be the default branch ...
so if we commit something to it, we can automatically close issues

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

I guess the github pages should still work, but we have to double check that.

**Comment by bastislack** [comment]
I changed it. Let's see if on the next release if the workflows with updating the main and gh-pages branches still work.
