### ISSUE TITLE
User tricks ids just incremented as the predefined tricks

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#172]
When playing around with the app I added some new tricks. Now I just updated the tricklist and the combolist and in the predefined combo it was showing one of my 'dummy' tricks instead of a trick that was just now added to the tricklist. I saw that the ID of my dummy trick was 10203. Shouldn't the user tricks start from 1?

**Comment by bastislack** [comment]
I think I found the issue!
When you create a new trick the id is 1.
When you delete a trick from the predefinedTricks then this id is stored in the userTricks db and then every new trick just increments from this id!
See screenshot:
<img width="739" alt="Screenshot" src="https://user-images.githubusercontent.com/74077179/151674833-89d6baed-5e80-4f4a-bee4-941764b9324b.PNG">

**Comment by weberax** [comment]
nice, ok. We should probably find the ids for new tricks differently.
Maybe with a function in the db.js which gives out a new id which is not used yet in both tables...
and than we could also think of changing the ids of the predefined tricks starting from 0.
This I think can be done with an db upgrade without affecting the users...
