### ISSUE TITLE
Long names without space can be covered by 'edit' button

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#175]
<img width="221" alt="Screenshot" src="https://user-images.githubusercontent.com/74077179/151674737-5990b833-230d-4348-8949-8777504e62ec.PNG">

**Comment by weberax** [comment]
![image](https://user-images.githubusercontent.com/44447528/173085603-97048eb5-eda5-4150-a969-d2a58737e6b8.png)
this seems to work now
