### ISSUE TITLE
When a trick is deleted combos that include this trick don't update the stats.

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#181]

**Comment by rorystephenson** [comment]
What about, instead of deleting the trick, marking it as disabled? Disabled tricks wouldn't show up in the trick list and wouldn't be choosable for new combos but could be visible in existing combos.

**Comment by bastislack** [comment]
Nice! Actually I think "deleting" tricks right now is kind of disabling it because we just add the trick to the userTricks db with the property "deleted: true". So maybe we can really say that it will just still exist in the combos that use it and can also still be accessed (meaning that we can go to the trickDetails screen) from there.
