### ISSUE TITLE
Consecutive tricks checkbox not working

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#183]
![Screenshot from 2022-01-31 21-04-19](https://user-images.githubusercontent.com/74077179/151864684-585cfc68-f4fc-48cd-aa18-f5cd67f9049c.png)

**Comment by bastislack** [comment]
Even when the checkbox is disabled consecutive tricks are generated.

**Comment by weberax** [comment]
fixed with #213
