### ISSUE TITLE
update frequencies of users / General  database update

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#184]
Because we added another frequency in a1941aa2 (`Often`), the previous frequencies like `Generally` and `Always` are downgraded...
We could implement a database update so, when updating the app to this newer version (when we next time merge the main), so that all frequencies with the value `5` and `6` are incremented by one.

**Comment by weberax** [comment]
@bastislack we should wait with the next merge for this....

**Comment by weberax** [comment]
also in #116 the new recommendedPre... are only updated in the predefined tricks table, therefore not shown for tricks where the user modified the tricks.
Should we consider also forcing these updates into the userTricks table?

**Comment by bastislack** [comment]
> @bastislack we should wait with the next merge for this....

I agree to wait for this before we update the app.

> also in #116 the new recommendedPre... are only updated in the predefined tricks table, therefore not shown for tricks where the user modified the tricks. Should we consider also forcing these updates into the userTricks table?

I think it is fine if we just have this property on the predefined tricks for now.
