### ISSUE TITLE
new Trick or Combo needs refreshing to show up

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#186]
after 450ce1e (#172), when you add a new trick or combo it does not show it directly in the TrickList, only after refreshing...

**Comment by weberax** [comment]
was this always the case, but we just never noticed it, because we where overriding other tricks?

**Comment by bastislack** [comment]
Maybe we didn't notice because we were overriding existing tricks!
In #172 I realized that something was wrong when adding the predefined combos, looking at one of them and instead of 'Orbital' is was 'Test' :D

**Comment by weberax** [comment]
ok, @bastislack can you look into this. I won't be able to do something in the next couple days
