### ISSUE TITLE
Changing stickFrequency of user made trick creates a copy of the trick

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#187]
The user made trick doesn't change but a new copy with the selected stickFrequency is created. Probably related to #172.

**Comment by weberax** [comment]
oh, I didn't test it enough... I just committed with 2% battery and no
option to charge ;)

**Comment by bastislack** [comment]
I don't know why but it is working fine right now...

**Comment by bastislack** [comment]
Nevermind! Probably I was using the old db version before that's why it worked :D
