### ISSUE TITLE
beginner friendly

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#209]
I heard now multiple times the feedback, that the app (especially the lvl0 tricks) are not really beginner friendly ...
I think we should try to make this app also, so beginners can use it to approach the freestyle sport.

ideas:
- we have to do something with the lvl0
   I mean it's kind of broken, chestroll should not be one lvl harder than chest to feet....
  
- maybe something like a beginner roadmap?
   something extra from the normal tricklist, just for beginners, not based on lvls but rather on trickprogressions (chestt -> chestroll  -> chest to feet -> chestroll to feet ...)  
   maybe with a skilltree #210

**Comment by bastislack** [comment]
Yes we definitely have to do something about this.
But the levels should actually reflect the roadmap for beginners so I would just suggest to reorder the levels (lvl 0 something you can do in your first ever session without any slackline experience).
I wanted to sit down with Rebekka and do this as we have some more references to trick difficulties in the lower levels with her now.

**Comment by bastislack** [comment]
We will work on updating the difficulties.
The skilltree is a nice idea, let's keep #210 going :)
