### ISSUE TITLE
Page crashes when opening in private Firefox window

### ISSUE THREAD

**Issue by JulianDietzel** [bastislack/highline-freestyle#214]
### Problem
When opening the website ([https://www.highline-freestyle.com/](https://www.highline-freestyle.com/)) in a private Firefox Window the website shows only a white page and two error messages are displayed in the console ([see below](#error-log)). 

### System
The problem could be reproduced on 
- Ubuntu 20.04 (Firefox Version 100.0.2)
- Android 10 (Firefox Version 101.1.1)

### Steps to reproduce
1. In Firefox click the Hamburger-menu (three bars) in the top right
2. Click "New private window"
3. In the newly opened window open the website ([https://www.highline-freestyle.com/](https://www.highline-freestyle.com/))

### Error log
This is the full log of three messages from the Firefox console after opening the page:

**Log**
```
supported: false main.js:2:598061
```
**Error**
```
Object { _e: Error, name: "DatabaseClosedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }
​
_e: Error: 
​
inner: Object { _e: Error, name: "InvalidStateError", message: "A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", … }
​
message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations."
​
name: "DatabaseClosedError"
​
stack: ""
​
<prototype>: Object { stack: "", … }
main.js:2:222384
```
**Error**
```
Uncaught (in promise) 
Object { _e: Error, name: "DatabaseClosedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }
```

**Comment by bastislack** [comment]
Thanks for the report!
@weberax This has to do with Dexie right?

**Comment by weberax** [comment]
Yes, this is because Firefox doesn't allow access to the storage in incognito mode.

I will fix this by catching the error and prompting the user to not use incognito.
