### ISSUE TITLE
optional local backup / import export database

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#215]
Include an Option to Export and import a databasefile, stored locally.
Mainly for the people who keep losing their data, because of not enough storage on the phone ( Sascha :( )

**Comment by bastislack** [comment]
Nice! Wouldn't the fix that you did some time ago also work for this? I think it's only on the develop branch for now.

**Comment by weberax** [comment]
The import feature does not work on most devices ....

So far it only works on Desktop Firefox, but **only with the _Web Developers Tolls_ open**.

**Comment by weberax** [comment]
oh, duplicate with #221 lets use the separate issue
