### ISSUE TITLE
Update difficulty levels

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#216]
Augustin is collecting some opinions on trick levels and we will use the results to update the difficulty levels

**Comment by bastislack** [comment]
Hey @JulianDietzel!
First of all, thanks a lot for your contributions and feedback, I am super happy about your help!

As you already noticed, there are quite a lot of tricks in the app that don't really fit in the level where they are right now and we definitely need to make quite some changes.

### Regarding your first point:
The reason why I initially wanted to have level 0 tricks, was because they were meant to be basic transitions that are not really tricks. This notion of basic transitions came from the fact that many already experienced highliners that started freestyling first did tricks like Sit Bounces before doing Korean Rolls or Panic Rolls. Obviously, looking at all the levels now, this doesn't make sense as the 'basic transitions' are for sure harder than the tricks in level 1.

One question that resulted from this is: 'Who is this app aimed for?'. Because if we target experienced highliners that just start their freestyling journey, obviously a Korean Bounce will be super easy for them. However, if we aim to provide a guide for beginners, anything that starts or ends on your feet is already quite advanced. I think that in the future it will be more common to see people having their first highline sessions without having any (or only little) experience on slacklines. That's why I think we should design the app to provide the best guide for these users.

#### What does that mean for level 0 tricks?
I planned to completely remove Level 0 as Level 1 should contain the tricks, that people can do in their very first sessions with no prior experience at all (just as you suggested as well). For the tricks that are currently in Level 0 we will try to find better suited levels (also taking your feedback into consideration).

### Regarding your other points:
In general, the topic of trick difficulties is quite a challenge, as noone is able to 'accurately' assign a difficulty to a trick. Everybody has different styles, preferences, and backgrounds from other sports that will make everyone's journey very unique. For competitions, however, it is quite important to be able to judge difficulties 'objectively' so we will try to assign levels as 'accurately' as possible. The levels as they are assigned right now is based on a poll that we did quite long ago and the refinement of those results, that I did with Ian and Sakalomo. For tricks that have been added since then I just gave my best guess of the difficulty level.

Since then a lot has changed and some people have tried to come up with methods that can take multiple people's opinion and average the results. However, until now it doesn't seem like we have found an 'optimal' method yet. Hopefully, we will figure this out in the coming years :)


### How can we use the app to get feedback about the difficulties?
It would be great if we could use the app to collect user's opinions on the difficulty.
One example where I saw this being done is the [Kilter Board app](https://play.google.com/store/apps/details?id=com.auroraclimbing.kilterboard&gl=US), where after completion of a boulder problem you could give your grade suggestion and the problem's difficulty is averaged from the votes (not 100% sure about this though!). In the Kilter Board app you can choose the grade directly but when you inspect the votes, usually the ones that suggest different grades only change it by one grade (e.g. 6b+ instead of 6b). 
So an idea I had for our app is to just include something like up-/downvote buttons for each trick. Over time we can analyse how many upvotes and downvotes a trick has and decide if we want to change the level.
What do you think about this @JulianDietzel, @rorystephenson, @weberax, @Felix-Hmpl?

**Comment by rorystephenson** [comment]
I think as a starting point it would be awesome if users could choose their own difficulty for a trick if want to. Automatically adjusting tiers based on user ratings would be awesome in the future. As a starting point I think it would already be great if users can set what tier they think a trick belongs to and see what the general user opinion is for a trick's difficulty. For the latter we need to start using a database with users which would open up a ton of cool possibilities.

**Comment by bastislack** [comment]
We updated the difficulties for now. The goal is to have a button to up/downgrade tricks in the future (see #257).
