### ISSUE TITLE
Left Navbar not responsive to screen height

### ISSUE THREAD

**Issue by JulianDietzel** [bastislack/highline-freestyle#231]
The navbar on the left side gets cut off if the screen is not high enough. The navbar is not scrollable, so all cut off options are unavailable. This can be an issue when using the app on a computer and scaling it to that size or on when using it on tablets of certain sizes.
The issue might get worse with additional sorting options or if links to for example an imprint are added.

![Screenshot from 2023-03-05 12-01-43](https://user-images.githubusercontent.com/33333283/222956559-aea38822-d454-4b6a-bf82-107f65e11b35.png)

**Comment by JulianDietzel** [comment]
I would propose to do one of two things:
1. Make the navbar scrollable when it gets cut off
2. Move the sorting options out of the navbar. Therefore the navbar becomes so short that the issue will not occur under any reasonable circumstances anymore. The sorting options could be moved next to or underneath the search bar (maybe depending on the screen size), as a drop down menu.

I personally lean towards option 2. It should be fairly easy to implement and the result will visually reflect the semantic connection between the search bar and the sorting options.

**Comment by bastislack** [comment]
I like the second option too. I think it would be great to have a 'filter bar' where users can apply different filters and maybe the sorting options would nicely fit in there?
