### ISSUE TITLE
iOs: App crashes on start up

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#241]
This error comes up on start up of the app for an iOs device. Final part of the message is: "(evaluating 't in n')".

![IMG-20230304-WA0002](https://user-images.githubusercontent.com/74077179/224818893-22e28240-fa17-4446-9b1d-867b2818b4db.jpg)

**Comment by Felix-Hmpl** [comment]
I get a similar message, when I compile the dev version and open it in chrome. See #243

**Comment by weberax** [comment]
I think this is based on some database corruption (no idea when it actually happened and what caused it), like some other errors. Resetting the App like described https://github.com/bastislack/highline-freestyle/issues/224#issuecomment-1694383128 could fix it.
I can not test it on IOS, can someone still recreate this?

**Comment by weberax** [comment]
Then I would say we close this for now, this will probably not be important in the future
