### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#242]
[@WaldemarLehner](https://github.com/WaldemarLehner) was talking about migrating this repo to TypeScript.
This could save us a lot of headaches with runtime errors when types are not as expected.

Are there any disadvantages that would keep us from changing to TypeScript?
@rorystephenson @weberax

**Comment by weberax** [comment]
Sounds good to me

**Comment by rorystephenson** [comment]
Yep it's definitely nicer to work with.

**Comment by WaldemarLehner** [comment]
@bastislack 
I think this can be closed as its happening on the Rewrite :D

**Comment by JulianDietzel** [comment]
Yes, this gets addressed in the rewrite at the moment. As the rewrite uses TypeScript from the start, this is not an ongoing issue and I'll therefore close it.
