### ISSUE TITLE
Reference to other tricks

### ISSUE THREAD

**Issue by Felix-Hmpl** [bastislack/highline-freestyle#244]
As many of the tricks in highline freestyle are connected, in my opinion it would make sense to include references.  

For example: "_From Hanging swing your legs beside your hands (similar to a **Sick Nasty** movement) and go into a **Back Sofa Roll**._"  
This tricks description contains refers to two other tricks, but they are not _linked_ in any way. Currently, you have to remember the name, go back to the list, and search for the trick there, if you want some information about one of them.

I'm sure it would add to the usability, if each trick contained references to other tricks in the form of buttons or links that directly take you there.

### Idea
Add a list of references to every trick.  
In TrickDetails have a section "_See also_" that contains the list of references in the form of buttons or links. We would need to make some changes to the database in that case.  

If you have some thoughts on this, please comment  :)

**Comment by weberax** [comment]
is this not a duplicate to #206?

**Comment by Felix-Hmpl** [comment]
> is this not a duplicate to #206?

Ah thanks, I totally overlooked this issue.  
If I understand correctly, in #206 the idea is to include links in the description. I also thought about that and figured that this could get messy. Thats why I suggested having a list of references instead.  
But you are right, the "issue" is the same so it is a duplicate :) I will add my thoughts to #206 later

**Comment by weberax** [comment]
perfect, so close this
