### ISSUE TITLE
Inconsistent size of h3 heading on TrickDetails.js

### ISSUE THREAD

**Issue by JulianDietzel** [bastislack/highline-freestyle#248]
On the TrickDetails page, the h3 heading has an incredibly small font size. This is not the case on other pages. I don't know what causes this, but if it is happening intentionally I believe an unmodified h6 heading should be used instead of scaling down the h3 one.

Headers h1 to h6 when displayed on the TrickDetails.js page:
![Screenshot from 2023-03-17 15-22-45](https://user-images.githubusercontent.com/33333283/225933254-739d1cc5-1a18-4503-9dd8-d9ff3ed8bb73.png)

**Comment by bastislack** [comment]
Looks like this entry in `index.css` is to blame:
```
.trick-details h3 {
  margin: 7px auto;
  font-size: 0.8em;
}
```
Using h6 definitely makes more sense :D
