### ISSUE TITLE
Bootstrap vs. MUI?

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#252]
We are mostly using [Bootstrap](https://getbootstrap.com/) right now, however, we could also use [MUI](https://mui.com/core/) as an alternative.
MUI has a nice slider, which right now we are using from a separate package. The slider does not justify rewriting everything with MUI but we could just think about whether we want to continue with Bootstrap or switch to MUI (or something else like Tailwind CSS).

**Comment by WaldemarLehner** [comment]
I can vouch for Tailwind, having used it with [Vue3 for my Portfolio rewrite](https://waldemarlehner.de/en) and [Next.js/Remix for my Bachelor's Thesis](https://gitlab.com/waldemarlehner-hrw/ws2022/bachelorarbeit/).

One thing you need to consider is that Tailwind is *not* a component library like MUI, but a CSS Utility — which means you would still need some sort of library for Ranges, special input fields, etc... 
(PS: I am not sure if I would call Bootstrap a Component or a CSS Library, but I would argue that Tailwind is way more "low-level" than Bootstrap or MUI)

It does not really do anything other than add CSS classes while only importing the ones it finds when searching for strings in the source file. 

Styling components is cumbersome in React and I feel like simply being able to add the classes in HTML should get you the desired result fairly easily. 

Just beware that most of the HTML will be class definitions: 
![image](https://user-images.githubusercontent.com/27686785/228031794-adfcd398-299c-48f9-8cd1-8cc567b59730.png)

**Comment by WaldemarLehner** [comment]
Small amendment: There is also [Flowbite](https://flowbite.com/docs/getting-started/quickstart/). It's a **component** library build ontop of Tailwind. Flowbite does provide a [Range Component](https://flowbite.com/docs/forms/range/#range-slider-example) which is limited in that you cannot set two values inside the range (as in… there is only one selector). What might work is to import [react-range](https://react-range.netlify.app/?story=range--two-thumbs) and style it with tailwind for that specific use case.

**Comment by WaldemarLehner** [comment]
I also stumbled across this thing: https://daisyui.com/

Apparently it builds upon TailwindCSS and provides classes for common UI Elements. I might give it a try for another project and see how easy it is it work with

**Comment by JulianDietzel** [comment]
What would be the benefit to switch away from Bootstrap apart from having a nicer slider? Seems like every single Component would need to be rewritten if we were to switch, which is quite a bit of development overhead.

**Comment by bastislack** [comment]
@WaldemarLehner Would it be much overhead for you to change from Bootstrap to something else, while you are rewriting the app in TS?

**Comment by WaldemarLehner** [comment]
Not at all. In fact I would prefer TailwindCSS. I could copy most of the
building blocks from other projects.

**Comment by Dosbodoke** [comment]
I also think that Tailwind is the way to go. We can enhance the UI so much. Maybe I can give a try on it

But do you guys don't think that this task and migrating to vue #242 + ts #245 should be different tasks? If the UI will be exactly the same, we can recreate all the current styles on Tailwind. But if we need, for example, to insert or delete components to change the UI behavior, it can be risky whiteout TypeScript

**Comment by JulianDietzel** [comment]
I'd agree with @Dosbodoke that if we do a UI overhaul it should happen separately from the migration to Vite which already is getting tangled up with the migration to TS (for which there might be good reasons, but still the scope is already bigger than it needs to be).

**Comment by bastislack** [comment]
> Not at all. In fact I would prefer TailwindCSS. I could copy most of the building blocks from other projects.
Let's go with Tailwind then :)

And I guess it makes sense to keep the UI changes separate from the migration to Vite, except you (@WaldemarLehner) have good reasons to do it all at once.

**Comment by WaldemarLehner** [comment]
I can try to not touch the UI all that much. 
I will have to change the UI Component's internals as there are some patterns used that aren't that clean and that TS is not all too happy about.

**Comment by JulianDietzel** [comment]
This gets addressed in the rewrite. We settled on using TailwindCSS for styling with Shadcn as a component library (#305).
