### ISSUE TITLE
Youtube integration on Combo List is broken

### ISSUE THREAD

**Issue by DavidKaep** [bastislack/highline-freestyle#258]
The only predefined combo that currently has a youtube integration is `Basti's favourite #3` and it breaks with the error `YouTube is not defined`.

Steps to reproduce on both desktop and android:
Click on `Basti's favourite #3` in the Combo List

I tried manually adding youtube links to already predefined combos and they break in the same way so its a problem with the integration on that page.

Versions tested: 
- 2dd62c6 (current release)
- 78324c4c33b244a9267bedfa8ee2a2427b7c8d7d (current dev HEAD)

Maybe this is adressed by #256

**Comment by JulianDietzel** [comment]
Fixed in #256.
