### ISSUE TITLE
Would you be motivated for one week of Freestyle App Hackathon this year?

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#261]
I would love to have a litte coding meeting where we can discuss about the app and do some coding sessions.
Obviously, we would need to have some freestyle lines as well.
If @JulianDietzel and @WaldemarLehner are interested, we could do it in Germany, otherwise we could also go somewhere else in Europe?
Let me know what you think!

**Comment by WaldemarLehner** [comment]
Given that I started working full time this April I don't really have time
for that. But I'd generally be down to join in remotely if you do some
coding.

Sebastian Egger ***@***.***> schrieb am Mi., 3. Mai 2023,
18:55:

**Comment by JulianDietzel** [comment]
Sounds amazing :+1: . I'd be down for a meetup! Almost any place in Europe could work for me, though I suppose Germany is probably the best option. I'm quite flexible time-wise.

(I don't know where you guys live, but just in case that we already live closeish together: I currently live in Bavaria)

**Comment by bastislack** [comment]
@JulianDietzel Write me on Whatsapp: +4917644724944
