### ISSUE TITLE
Track personal progress - Set stick frequency (in trick details)

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#289]

**Comment by JulianDietzel** [comment]
Started working on this.

**Comment by JulianDietzel** [comment]
Will require updating the type of `stickFrequency` to `number`. I'm currently working on this and this comment should serve as a reminder to update the data diagram on https://github.com/bastislack/highline-freestyle/wiki/Backend-Overview before / when eventually merging the PR.

**Comment by JulianDietzel** [comment]
Implemented in PR #342

Only the wiki needs updating then this issue can be closed.

**Comment by JulianDietzel** [comment]
Update the docs inside the project and by that the diagram in the wiki. Check 903eb3b for details.
The feature is therefore fully implemented with the documentation updated. I will close the issue.
