### ISSUE TITLE
Modify DB Schema for tricks and combos

### ISSUE THREAD

**Issue by WaldemarLehner** [bastislack/highline-freestyle#300]
To not further bloat the #272 PR the correction of the schema should be done in a separate PR.

Combos should have a name (and no `alias` /  `technicalName`)
Tricks should have an `alias` and a `technicalName` (and no `name`)

Technical Hint: 
Do not forget about the drawio-Graphic!

**Comment by JulianDietzel** [comment]
Is this already implemented?

**Comment by WaldemarLehner** [comment]
nope. Feel free to impl :)

**Comment by JulianDietzel** [comment]
Fixed / Updated in PR #304
