### ISSUE TITLE
Show trick tips as list 

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#45]
In the csv file the tips are separated by ';'. Separate those tips and show them in a list.

**Comment by bastislack** [comment]
Using papa parse we can use the transform function (as shown here: https://abaganon.com/tutorials/papaparse.html) to convert the entry in the tricklist to an array and then store it as a multiEntry in Dexie.

**Comment by weberax** [comment]
I would say we don't need to store it as an multiEntry, this would just be useful if we would like make a selected query based on this. But because these are only tips, I think this would never happen.

I would suggest to solve this just on the displaying component...

**Comment by JulianDietzel** [comment]
I'd recommend creating a new table for the tricks. By my understanding, this would be the canonically correct way for a relational database schema (unless Dexie is doing something very unusual here).

This would mean creating a new table `TrickTips(TrickId, Tip)` and then, when loading a trick, querying the new `TrickTips` table for all entries with the id of that trick (`TrickId`). 

[Dexie Documentation for joins](https://dexie.org/docs/API-Reference#joining)
