### ISSUE TITLE
Will deleting the indexedDB still be necessary in the future?

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#49]
Sometimes the app doesn't load the levels of the tricks for me.
Is this just because the old version is still saved in my browser and thus I have to delete the DB and reload it?
Users should not encounter the need to do this.

**Comment by weberax** [comment]
Yes, it definitely would make much more sense. If we had all the tricks in one table also querying for specific ones, implementing filters, for example for creating combos or for just filtering the tricklist would be much easier...

But the only problem will be updating the tricklist.
We have to find a way to keep the own tricks and the tricks from the google sheet nice and separate, so when we update the sheet we don't overwrite any own tricks... And we have to keep the stickfrequency, when updating
