### ISSUE TITLE
Have multiple tricks/combos in one row depending on the screen size

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#57]
Right now on a phone there is one trick per row. It would be cool to have two or three (maybe the font size would need to change for tricks with long names?).

**Comment by Felix-Hmpl** [comment]
I did some adjustments in e4be67ef432d0d7b65b94b1a67a0723972793db5
The layout should produce two rows on a bigger screen
Two rows on a phone screen are making things look squishy in my opinion. 
![image](https://user-images.githubusercontent.com/60603136/141688496-1038a0eb-1a5e-411b-b006-9a4664a907cf.png)
Sould I try to make two rows look good, or should we keep one row on small screens?

**Comment by bastislack** [comment]
I was actually thinking of even more. Like maybe three columns. 
Here is a screenshot of the kendama app on full zoom. There it's almost 4 columns which is maybe too much, but I think three columns with a smaller fontsize could be nice. Also having boxes of the same size would make it look a bit better I guess.
![Screenshot_20211114-213941](https://user-images.githubusercontent.com/74077179/141697819-5d552385-4a8d-47c7-9ebc-13fcbb0ceb78.png)

What do you think?

**Comment by Felix-Hmpl** [comment]
Okay, I agree, with a smaller font size it looks quite nice 
7afb99aec0ae4b1765ec9586709f2b3704eecb21
I changed it to 2 columns for now, but I can change it to 3, should I?

**Comment by bastislack** [comment]
Let's try to go for three and see if we can make it look nice, otherwise we can stick with two.

**Comment by Felix-Hmpl** [comment]
![image](https://user-images.githubusercontent.com/60603136/142735928-9ed85b5e-6f70-4b33-8aa6-0289e58467b4.png)

 vs

![image](https://user-images.githubusercontent.com/60603136/142735945-fa284170-0e8f-4ad7-9f85-93ccf8da228e.png)


What do you like better?

**Comment by bastislack** [comment]
I like three better :)
