### ISSUE TITLE
Link bootstrap to puplic cache

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#60]
For testing I deployed the app under highline-fs.dynv6.net

If you check under the network tap in the developer tools, you can see that it tries to load bootstrap.css from my server. But it fails because I didn't put it there (I just uploaded all the files in the dist folder after `npm run prod`)

We should adjust the code, that in development it uses the local copy and in production a public version somewhere else.

**Comment by bastislack** [comment]
Maybe we can use 'react-bootstrap'. I haven't looked into it but it might be an easy option to remove the bootstrap.css dependency.

**Comment by weberax** [comment]
Are we anyway using bootstrap? @bastislack @Felix-Hmpl

I mean looks like everything works fine also without the bootstrap.css

**Comment by bastislack** [comment]
All the styles (e.g. the buttons) are the bootstrap styles so somehow it is working even though you don't have the bootstrap on your server.

**Comment by bastislack** [comment]
@weberax Is this still relevant?

**Comment by weberax** [comment]
I think this is resolved
