### ISSUE TITLE
Trickpreview button remove blue color

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#69]
When pressing down a trick-preview button (tricklist or combodetails) the button changes to a blur color.
Also when doing this on the phone and then sliding the finger to another place, the button stays blue.

Would be nice to remove the color but keep the press down effect

**Comment by Felix-Hmpl** [comment]
Removed coloring effect when hovering over buttons in TrickList
22c8d05989c30d37f80d5c5fd685fdadd8703032

**Comment by Felix-Hmpl** [comment]
Removed coloring effect when hovering in ComboDetails
c3416a02b1dfe096fe6a0dfe0382e878446427c2

**Comment by Felix-Hmpl** [comment]
Accidentally closed this. 
I removed the stuck hover effect, but the press down effect is very minimalistic. Gonna search for a nice effect.

**Comment by weberax** [comment]
this seems to be fixed as well
