### ISSUE TITLE
Iphone bug

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#76]
on Mikes Iphone, most of the TrickDetails don't work. Looks like it only affects the tricks with an youtube link....
Maybe #74 fixes this.

**Comment by weberax** [comment]
I tried a super quick fix, by chaning the youtube links to https, but It did not solve this problem.

**Comment by weberax** [comment]
maybe we should only load the video (show the iframe), after the user clicks someting

**Comment by Felix-Hmpl** [comment]
Could you specify "dont work" please, @weberax? I have no iPhone, so I unfortunately can't test it. Maybe a screenshot?

**Comment by weberax** [comment]
If you navigate on the iphone (safari and chrome) to a trick with a YouTube video (no video and Instagram video both works) you end up at a complete blank page without the navbar.
When you go back via the browser navigation you are still on a complete blank page, inly when you refresh there it atarta working again.

My guess is, that the vjdeo is not perfectly embedded and the ios browsers have different security restrictions.

**Comment by rorystephenson** [comment]
Should be fixed by 6015719ed2033c183cf443345c29823b2fd6dcef
