### ISSUE TITLE
Trick-Preview in Combo

### ISSUE THREAD

**Issue by Felix-Hmpl** [bastislack/highline-freestyle#80]
When viewing a combo it would be nice to make the Trick names clickable, to get to the Trick preview. 
Maybe a pop-up?

**Comment by bastislack** [comment]
They are already linked!
It's a link to the respective TrickDetails screen. With the BackButton you get back to your combo.

**Comment by weberax** [comment]
But not for the random combo screen yet...

We should also consider if we need the random comboscreen or if we can just use the combodetail screen also for the combo generator.

**Comment by bastislack** [comment]
I like the idea of reusing the combodetails screen!
