### ISSUE TITLE
Make youtube video loop

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#85]
Make the video loop between a start end end position. 
We can use the youtube api for that:
https://developers.google.com/youtube/iframe_api_reference#Events 

And this for accesing the api cleanly 
https://www.npmjs.com/package/react-youtube

Maybe also through thus package we will fix this problem #76

**Comment by weberax** [comment]
@bastislack can we add two more columns to the google sheet? The start end stop time.
Both non mandatory and but if we have them we'll loop the video otherwise we keep it like it is now.

**Comment by bastislack** [comment]
The start time is already given in the links provided in linkToVideo. But I will add a column for stop time (#87). Or do we need the start time in a separate column as well?

**Comment by weberax** [comment]
No i we don't need it, we can always get it from the url. But maybe it makes it easier, also for later adding more videos.

**Comment by bastislack** [comment]
Ok I gave this a shot but with the react-youtube package we have the problem that when "loop" is enabled, as soon as the video replays for the first time it doesn't start at the specified start time anymore.
I found something here:
https://webapps.stackexchange.com/questions/45884/have-an-embedded-youtube-video-loop-end-at-specified-time-every-time-it-plays
But I couldn't get it to work yet.

**Comment by bastislack** [comment]
Ok finally figured it out!
