### ISSUE TITLE
Fix Settings menu

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#89]
When the submenu for the sorting options opens it opens on the other side of the arrow (arrow points to the right but submenu opens on the left). 

![settings](https://user-images.githubusercontent.com/74077179/141657472-9be1167a-3566-4c43-80ca-fac59f7bff30.png)

**Comment by rorystephenson** [comment]
I'm having a look at some simple issues to get familiar with the code 🙂.

The menu does actually go on the right but only if there is space for it:
<img width="523" alt="Screenshot 2021-11-16 at 6 32 57 PM" src="https://user-images.githubusercontent.com/3683599/142036135-dc919638-8524-4b88-851f-d5906aa2312c.png">

We can improve this a bit by changing where the whole menu pops up by changing the alignment like so:

```patch
-    <Menu menuButton={<button className="btn"><BsGearFill/></button>} transition>
+    <Menu menuButton={<button className="btn"><BsGearFill/></button>} transition align="end">
```

Which makes the menu open more on the left relative to the gear icon and leaves more space:

<img width="498" alt="Screenshot 2021-11-16 at 6 44 24 PM" src="https://user-images.githubusercontent.com/3683599/142039993-87751365-b7f2-42dc-884a-58ff231131cc.png">

If there is still not enough space the submenu will still open on the left and the arrow looks weird.

Other alternatives:
- Set the submenu to open on the left and change the arrow to be a left arrow.
- Consider moving the sorting options out of the menu to some dedicated buttons (or something else) that's always visible (maybe even after the beta is live).

**Comment by bastislack** [comment]
Hey Rory!
Amazing to have your support :)
I guess as we will mostly use this app on mobile and the gear icon will be all the way to the right it would make sense to change the arrow and have it on the left side and also open the submenu on the left side.

**Comment by rorystephenson** [comment]
I've had a look and the menu library we're using doesn't seem to offer an easy way to change the arrow direction.

However I experimented with just removing the submenu altogether and it seems like a reasonable alternative to me. It also reduces the cliks/taps required to changer sorting by one. It looks like this:

<img width="272" alt="Screenshot 2021-11-18 at 9 43 22 PM" src="https://user-images.githubusercontent.com/3683599/142493812-afb46330-5285-4742-8438-e7070bf9d0ad.png">


What do you think?

**Comment by bastislack** [comment]
Oh this is nice! I like it :)
