### ISSUE TITLE
Fix production build

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#97]
The deployed site doesn't work right now. I am not sure if it was a commit that broke it or if it is related to the new domain setup.

**Comment by bastislack** [comment]
I think the source of the error is related to a0183c0.
@rorystephenson can you have a look at that?

**Comment by rorystephenson** [comment]
> I think the source of the error is related to [a0183c0](https://github.com/bastislack/highline-freestyle/commit/a0183c06beb64b2bc93b8e2f647310beb2bcd3e4). @rorystephenson can you have a look at that?

Strange that was actually a fix to get it working locally and it worked for me 🤔. I'm away from my computer for the next few days so I won't be able to fix this straight away, sorry.

**Comment by rorystephenson** [comment]
Should be working again! Sorry I was away from my computer longer than expected.
